/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sqs;

import static sqs.Publish.publish;

public class App {
    public static void main (String[] args) {
        publish(args[0]);
    }
}
