/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sqs;

import static sqs.Receive.receive;
import static sqs.Send.send;

public class App {
    public static void main (String[] args) {
        String queueName = "";
        switch (args[0]) {
            case "1":
                queueName = "QueueA";
                break;
            case "2":
                queueName = "QueueB";
                break;
            case "3":
                queueName = "QueueC";
                break;
        }
        send(queueName);
        receive(queueName);
    }
}
